### ISSUE TITLE
Uncaught (in promise)

### ISSUE THREAD

**Issue by fleischie** [kmohrf/stroll.js#1]
Hey @kmohrf . I like stroll.js a lot so far. :smile: 

I have the following issue, which is a little constructed and (maybe) mainly due to my lacking js-skills:
When having two consecutive calls to stroll, [`reject()`](https://github.com/kmohrf/stroll.js/blob/master/src/stroll.js#L97) is undefined.

Minimal working example:

``` html
<!DOCTYPE html>
<html>
  <body>
    <section>
      <h1>Stroll test</h1>

      <div style="height: 2000px"
           id="first">
        <p>Text.</p>
      </div>

      <div style="height: 2000px"
           id="second">
        <p>Text.</p>
      </div>
    </section>

    <script type="text/javascript" src="dist/stroll.js"></script>
    <script>
stroll('#second');
stroll('#first');

// alternatively a more sensible example
setTimeout(() => stroll('body', {duration: 5 * 1000}), 5 * 1000);
stroll('#second', {duration: 6 * 1000});
    </script>
  </body>
</html>
```

I know, that this is not the intended way of strolling to and fro. The strolling is cancelled, but I don't know what to make out of the error.

**Comment by kmohrf** [comment]
chromium/chrome reports if a promise was rejected and you didn’t define a catch handler. you can easily try that by calling `Promise.reject()` in your browsers console. maybe i should’t handle cancellation as rejection, because reject basically is for situations where i’d call throw otherwise. and i wouldn’t throw an exception if someones cancels scrolling.

**Comment by kmohrf** [comment]
there you go. fixed in v2 :)
